
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-dameng-com-v1-autonomy
  failurePolicy: Fail
  name: mautonomy.kb.io
  rules:
  - apiGroups:
    - apps.dameng.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - autonomies
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-dameng-com-v1-autonomy
  failurePolicy: Fail
  name: vautonomy.kb.io
  rules:
  - apiGroups:
    - apps.dameng.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - autonomies
  sideEffects: None
