# permissions for end users to edit dm8s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dm8-editor-role
rules:
- apiGroups:
  - apps.dameng.com
  resources:
  - dm8s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.dameng.com
  resources:
  - dm8s/status
  verbs:
  - get
