# permissions for end users to edit dms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dm-editor-role
rules:
- apiGroups:
  - apps.dameng.com
  resources:
  - dms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.dameng.com
  resources:
  - dms/status
  verbs:
  - get
