# permissions for end users to view dms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dm-viewer-role
rules:
- apiGroups:
  - apps.dameng.com
  resources:
  - dms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.dameng.com
  resources:
  - dms/status
  verbs:
  - get
